SRJPE/JPE-datasets

analysis/qc-checks/qa-ranges.Rmd

Updated the QA file. Ashley please review and confirm that the ranges look reasonable. I am happy to talk through if that is easier!

Moves qa ranges rmd to clean branch

---

data-raw/qc-markdowns/rst/lower-sac/tisdale/tisdale_camp_catch_data.Rmd
data-raw/qc-markdowns/rst/lower-sac/tisdale/tisdale_camp_catch_data_4mac.Rmd
data-raw/qc-markdowns/rst/lower-sac/tisdale/tisdale_efficiency.Rmd
data-raw/standard-format-data-prep/mark_recapture_standard_format.Rmd
data-raw/standard-format-data-prep/rst_catch_standard_format.Rmd
data-raw/standard-format-data-prep/rst_environmental_standard_format.Rmd
data-raw/standard-format-data-prep/rst_trap_standard_format.Rmd

There is a lot here but please give this a look when you get a chance. We can walk through together if that is easier.
This branch does a few things:
- pulls in  tisdale efficiency data (rmd script that pulls from CAMP) and adds to standard mark recapture
- pulls in tisdale catch, trap, environmental from CAMP and adds to standard format files
- improves performance of standard catch by moving case_when in dplyr to data.table
Note that there are still some loose ends that will be tied up next (Feather trap from CAMP, Knights environmental from CAMP, pulling in existing mark data from CAMP etc.)

Tisdale efficiency

---

data-raw/README.md
data-raw/template_using_googlecloud.Rmd

Added some documentation for the google cloud workflow. Please review and merge in when ready!

adds readme on setting up for google cloud

---

analysis/refomat_lad_table.R
refomat_lad_table.R

If you could do a quick review and merge that would be great!

Adds script to reformat lad table to give multiple ranges when needed

---

data-raw/standard-format-data-prep/standard_adult_redd_data.Rmd

erin - i merged in the standard_redd_data branch to main and then noticed an issue that was causing an error when uploading data to the cloud. can you review this change really quick so i can merge the change into main?

fixes gcs upload in standard redd so upload will work

---

data-raw/standard-format-data-prep/mark_recapture_standard_format.Rmd

I lost track of this change - this just fixes one typo.

fixes site typo

---

data-raw/standard-format-data-prep/mark_recapture_standard_format.Rmd
data-raw/standard-format-data-prep/rst_catch_standard_format.Rmd
data/standard-format-data/pull_data.R
scripts/prep_data_for_model.R

When I was preparing the data for the next update for Josh noticed a few issues which are resolved here. Please double check these changes!

Data update dec2022

---

analysis/qc-checks/plots_for_rst_pilot_project_QC.R

PR for plots used in QC interface. should not effect any other files in the repository! Please review and merge

Plots for qc interface

---

data-raw/qc-markdowns/rst/butte-creek/butte_camp_data_pull.Rmd
data-raw/standard-format-data-prep/flow_standard_format.Rmd
data-raw/standard-format-data-prep/rst_catch_standard_format.Rmd
data-raw/standard-format-data-prep/rst_effort_standard_format.Rmd
data-raw/standard-format-data-prep/rst_trap_standard_format.Rmd
scripts/prep_data_for_model.R

Erin - Please review when you have time. I opened issues for all of Josh's comments and addressed all issues within this branch. I did not close out the issues yet because I was hoping you could double check them. Thank you!

Standard data updates dec2022

---

data-raw/standard-format-data-prep/mark_recapture_standard_format.Rmd
data-raw/standard-format-data-prep/rst_catch_standard_format.Rmd
data-raw/standard-format-data-prep/rst_environmental_standard_format.Rmd
data-raw/standard-format-data-prep/rst_trap_standard_format.Rmd

Update butte creek data in standard format datasets - I made the following changes: 
- Updated subsite names so we didn't have "okie fyke trap" and "okie dam fyke trap" - changed all to "okie dam fyke trap" 
- Updated all butte datasets to remove days that only fyke trap sampling 
Additionally I was getting and error with the mutate statement ifelse( , ,`NA_real_`) so I changed `NA_real_` to `NA` 
I also was having some speed issues with the catch script. I found that adding an ungroup() after the summarize statements improved performance drastically.

Updates butte trap to exclude fyke only days

---

scripts/prep_data_for_model.R

This code adds fish origin to the weekly efficiency summary and also includes some code to analyze discharge across efficiency trials in the same week.

adds fish origin and summaries of efficiency data

---

data-raw/standard-format-data-prep/adult_passage_estimate_standard_format.Rmd
data-raw/standard-format-data-prep/carcass_cjs_estimates_standard_format.Rmd

Please review when you get a chance
- butte creek vaki estimates added to passage estimate standard format
- butte creek and yuba river cjs estimates added to new standard format rmd. we can add to this when we get the feather estimates and also add CI/uncertainty when we get those values.

Adult standard format updates

---

data-raw/standard-format-data-prep/carcass_cjs_estimates_standard_format.Rmd

Quick change to add in Feather Rive CJS estimates!

adds feather cjs estimates

---

data-raw/standard-format-data-prep/flow_standard_format.Rmd

sorry about this - just fixes a typo reading in lower feather so that we have the correct data. already pushed to cloud

fixes typo in standard flow

---

data-raw/standard-format-data-prep/flow_standard_format.Rmd
scripts/prep_data_for_model.R

Added a couple of clean up commits to add back in sites/site groups for feather and then updated some of the week info in prep data for josh so we weren't introducing NA weeks

Josh clean up

---

data-raw/qc-markdowns/rst/deer-creek/deer_2022_2023_qc.Rmd
data-raw/qc-markdowns/rst/mill-creek/mill_2021_2022_qc.Rmd
data-raw/qc-markdowns/rst/mill-creek/mill_2022_2023_qc.Rmd

this should have both the 2021-2022 data branch and the 2022-2023 data!

Mill deer 2022 data

---

scripts/prep_data_for_model.R

Created a table of `year`, `site_group`, `site` for Josh to use on Feather River.

creates csv for annual feather site selection

---

data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/battle-creek/battle_creek_redd_qc.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/clear-creek/clear_creek_redds_survey_qc.Rmd
data-raw/standard-format-data-prep/standard_adult_redd_data.Rmd

- keeps all species in battle redd markdown
- keeps all species in clear redd markdown
- modifies standard redd markdown to account for species in battle and clear files

Update battle clear redds

---

data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-river-redd-survey-qc-checklist-2013.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-river-redd-survey-qc-checklist-2014.Rmd
data-raw/standard-format-data-prep/standard_adult_redd_data.Rmd

Updated 2013 & 2014 dates to fix NA values. I had to do a bit of a weird split and recombine because using a mutate ifelse was causing issues with different date types. 
I reran the combined redd script for feather and reran the standard redd script, saving updated tables to jpe-dev-bucket.

Feather na redd dates

---

data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/battle-creek/battle_holding_survey_qc.Rmd
data-raw/standard-format-data-prep/holding_standard_format.Rmd

Holding data checks

---

data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/battle-creek/battle_carcass_data_qc.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/butte-creek/butte-2017-2020-individual-qc-checklist.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/clear-creek/clear_creek_carcass_survey_qc.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-carcass-2002.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-carcass-2003.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-carcass-2004.rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-carcass-2005.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-carcass-2006.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-carcass-2007.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-carcass-2008.Rmd
data-raw/qc-markdowns/adult-holding-redd-and-carcass-surveys/feather-river/feather-carcass-survey-qc.Rmd
data-raw/standard-format-data-prep/carcass_cjs_estimates_standard_format.Rmd
data-raw/standard-format-data-prep/standardized_carcass.Rmd

closes #153 
adds 2019 butte data. created separate issue for adding in cjs estimate confidence intervals

Carcass dat achecks

---

data-raw/standard-format-data-prep/standard_adult_redd_data.Rmd

Remaining standard redd issues

---

data-raw/qc-markdowns/adult-upstream-passage-monitoring/deer-creek/extract_deer_upstream_estimates_from_raw_files.R
data-raw/standard-format-data-prep/adult_passage_estimate_standard_format.Rmd

closes #151 
- adds Deer and Mill
- should we add the comments from the notes in this issue into the .Rmd for posterity?

Upstream passage c is

---

analysis/adult-reach-analysis.R
data-raw/standard-format-data-prep/holding_standard_format.Rmd
data-raw/standard-format-data-prep/standard_adult_redd_data.Rmd
data-raw/standard-format-data-prep/standardized_carcass.Rmd

Reach standardization adult data

---

data-raw/standard-format-data-prep/adult_upstream_passage_standard_format.Rmd

Liz - Can you review when you get a chance? These edits add the Battle "spawning-building" dataset to the standard passage data. I did some initial checks and there should not be overlap or double counting between the two types of data. A follow up question we will want to ask on EDI is - what is the run for spawning-building and verify that removing fish returned to hatchey make sense.

Battle spawning building closes #182

---

data-raw/standard-format-data-prep/carcass_cjs_estimates_standard_format.Rmd

adds in butte cjs confidence intervals and pushes up to google cloud
